### ISSUE TITLE
Changes style=all_docs fails sometimes

### ISSUE THREAD

**Issue by nick-thompson** [pouchdb/couchdb-harness#2]
The test on line 476 of the `changes.js` test file fails every now and then, but usually succeeds. The response returned from the previous call to '/_changes?style=all_docs&since=2' returns an empty result set in the case that the test fails.

Not sure why that's happening, but I'm curious about `Pouch.merge.collectLeaves` being called on a partial rev tree since the server will return only part of the changes with the `since` parameter: https://github.com/daleharvey/pouchdb/blob/master/src/adapters/pouch.leveldb.js#L577

@daleharvey can I get your thoughts on that? Not sure what else the cause might be... I'll look into it more tomorrow.

**Comment by marten-de-vries** [comment]
The lines described have been run in Travis against express-pouchdb quite a bit by now, and I've never seen this. Closing.
